modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "filenameclean"
version = "${version}"
displayName = "FileNameClean"
authors = "TeamPotato"
description = '''
A Files Cleaner.
'''